<div class="row">
<div class="col-sm-6">

<form action="<?php echo $this->url('home')?>users/add" method="post" class="add_user">
  <div class="form-group">
    <label for="first_name">First Name:</label>
    <input type="text" class="form-control first_name" id="first_name" name="first_name" value="<?php echo @$formData['first_name']?>">
  </div>
  <div class="form-group">
    <label for="last_name">Last Name:</label>
    <input type="text" class="form-control last_name" id="last_name" name="last_name" value="<?php echo @$formData['last_name']?>">
  </div>
  <div class="form-group">
    <label for="last_name">Mobile:</label>
    <input type="text" class="form-control mobile only_numeric" id="mobile" name="mobile" value="<?php echo @$formData['mobile']?>">
  </div>
<div class="form-group">
    <label for="email">Email address:</label>
    <input type="text" class="form-control email" id="email" name="email" value="<?php echo @$formData['email']?>">
  </div>
  <div class="form-group">
    <label for="pwd">Password:</label>
    <input type="password" class="form-control password" id="pwd" name="password" value="<?php echo @$formData['password']?>">
  </div>
  <input type="hidden" name="id" value="<?php echo @$formData['id']?>">
  <button type="submit" class="btn btn-default">Submit</button>
</form>
</div>
</div>
